# -*- coding: utf-8 -*-
"""VisualVgg16testfinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16myLjbDxbmKbWh2vSWJQrpyJk44Zgvzq
"""

#lineone:Visualizing VGG16 model 
#http://image-net.org/about-stats
#https://arxiv.org/pdf/1409.1556.pdf
#below code has been tested and executed only in colab.research.google.com .For faster execution please make sure you have enabled GPU from notebook settings before execution

# Dependencies: pydot is used internally by keras.utils.model_to_dot (no direct import needed).
# Note: On Windows, install the Graphviz system binary (e.g. winget install Graphviz.Graphviz) and add to PATH.

#you are importing preprocess_input and decode_predictions from vgg16 model
#remember each model has its own preprocess_input and decoding functions when you are replication this for other 
#models make sure you importing from respective model
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np

model=VGG16(weights='imagenet',include_top=True)
#if you change include_top=False predict wont work

#This is the VGG model which we used - a text based description
model.summary()

#for visualizing model
from keras.utils import model_to_dot, plot_model
try:
    from IPython.display import SVG
except ImportError:
    SVG = None

#block representation of the model
try:
    if SVG:
        SVG(model_to_dot(model).create(prog='dot',format='svg'))
except Exception as e:
    print(f"Graphviz SVG visualization skipped (requires Graphviz binary installed): {e}")